name: HPC Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: mpi4py/setup-mpi@v1

      - name: make omp
        run: make omp_
      - name: make mpi
        run: make mpi_
